#!/usr/bin/env ruby

Root = File.join( File.dirname(__FILE__), '..')
require Root.join('config/environment')

Runfile = Root.join('tmp/playback.run')
File.touch(Runfile)
RunningSince = Time.now

while File.mtime(Runfile) < RunningSince 
  project = Project.next_in_queue
  project.play!
end




