#!/usr/bin/env ruby
#
require 'pathname'

Root = Pathname.new(File.expand_path( '..', File.dirname(__FILE__) ) )
require Root.join('config/environment')

Runfile = Root.join('tmp/playback.run')
File.touch(Runfile)
RunningSince = Time.now

while File.mtime(Runfile) < RunningSince 
  project = Project.next_in_queue
  puts "running #{project.name}"
  project.play!
end




